# Generated by Django 3.1.7 on 2021-03-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_destination_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='username',
        ),
    ]
