# Generated by Django 3.1.7 on 2021-03-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20210320_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isrelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.destination')),
            ],
        ),
    ]
