# Generated by Django 3.1.7 on 2021-03-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='isrelated',
            field=models.CharField(max_length=100),
        ),
    ]
